name: "Terraform Lint Scan"
description: "Run Terraform linting"

inputs:
  ref:
    description: 'Git ref to scan'
    required: false
    type: string
  scan-path:
    description: 'Path to IaC files (Terraform, YAML, etc.)'
    required: false
    type: string
    default: "."

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      id: repo-checkout
      uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

    - name: Set up TFLint
      id: tflint-setup
      uses: terraform-linters/setup-tflint@v4

    - name: Print TFLint version
      id: tflint-version-check
      shell: bash
      run: tflint --version

    - name: Init TFLint
      id: tflint-init
      shell: bash
      working-directory: ${{ inputs.scan-path }}
      run: tflint --init

    - name: Run TFLint
      id: tflint-scan
      shell: bash
      working-directory: ${{ inputs.scan-path }}
      run: |
        tflint -f json